## YAML Template.
---
spring:
  application.name: payroll-reactive-lambda-service
  lifecycle.timeout-per-shutdown-phase: 30s
  jackson:
    default-property-inclusion: non-default
    serialization:
      indent-output: true
  profiles:
    active: dev #,prod
  main: 
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:h2:mem:payroll-reactive
    driverClassName: org.h2.Driver   
    username: sa
    password:
  h2:
    console.enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties.hibernate.jdbc.time_zone: UTC
    defer-datasource-initialization: true
    hibernate.ddl-auto: create-drop
